system:
  guidance_type: "controlnet-guidance"
  guidance:
    control_type: "normal"
    min_step_percent: 0.05
    max_step_percent: 0.8

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "SG161222/Realistic_Vision_V2.0"
    prompt: "Elon Musk, RAW photo, (high detailed skin:1.2), 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"
    negative_prompt: "(overexposed, underexposed, out of focus, deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime:1.4)"
