name: "prolificzero123"
tag: "PDdef_${data.random_camera.height}_${rmspace:${basename:${data.image_path}},_}_${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "single-image-datamodule"
data: # threestudio/data/image.py -> SingleImageDataModuleConfig
  image_path: ???
  height: 192
  width: 192
  default_elevation_deg: 0.0
  default_azimuth_deg: 0.0
  default_camera_distance: 3.2
  default_fovy_deg: 20.0
  random_camera: # threestudio/data/uncond.py -> RandomCameraDataModuleConfig
    batch_size: 4
    width: [128, 512]
    height: [128, 512]
    resolution_milestones: [5000]
    camera_distance_range: [3.2, 3.3]
    fovy_range: [20.0, 20.0]  # Zero123 has fixed fovy
    elevation_range: [-10, 60]
    camera_perturb: 0.
    center_perturb: 0.
    up_perturb: 0.
    eval_elevation_deg: ${data.default_elevation_deg}
    eval_camera_distance: ${data.default_camera_distance}
    eval_fovy_deg: ${data.default_fovy_deg}
    # light_position_perturb: 1.0
    # light_distance_range: [2.8, 3.3]
    # batch_uniform_azimuth: False
    n_val_views: 30
    n_test_views: 120

system_type: "prolificzero123-system"
system:
  geometry_type: "implicit-volume"
  geometry:
    radius: 2.0
    normal_type: null # voletiv: CHECK

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true   # voletiv: CHECK

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    # return_comp_normal: ${gt0:${system.loss.lambda_normal_smooth}}        # voletiv: CHECK!
    # return_normal_perturb: ${gt0:${system.loss.lambda_3d_normal_smooth}}  # voletiv: CHECK!

  prompt_processor_type: "no-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: ""
    prompt: ""

  guidance_type: "zero123-vsd-guidance"
  guidance:
    pretrained_model_name_or_path: "./load/zero123/105000.ckpt"
    pretrained_config: "./load/zero123/sd-objaverse-finetune-c_concat-256.yaml"
    # pretrained_model_name_or_path_lora: "./load/zero123/105000.ckpt"
    # claforte: this should be from "./load/zero123/105000.ckpt" or something like that:
    pretrained_model_name_or_path_lora: "/admin/home-vikram/zero123xl/20230605_last.ckpt"
    pretrained_config_lora: "./load/zero123/sd-objaverse-finetune-c_concat-256.yaml"
    vram_O: ${not:${gt0:${system.freq.guidance_eval}}}
    cond_image_path: ${data.image_path}
    cond_elevation_deg: ${data.default_elevation_deg}
    cond_azimuth_deg: ${data.default_azimuth_deg}
    cond_camera_distance: ${data.default_camera_distance}
    guidance_scale: 7.5
    min_step_percent: 0.85
    max_step_percent: 0.99
    max_step_percent_annealed: 0.5
    anneal_start_step: 5000

  freq:
    n_ref: 2
    ref_only_steps: 0
    guidance_eval: 0  # must not be a multiple of system.freq.n_ref
    ref_or_zero123: "accumulate" # can be "accumulate" or "alternate"

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_rgb: 1. # was 200
    lambda_mask: 50.
    lambda_depth: 1.
    lambda_vsd: 1.
    lambda_lora: 1.
    lambda_orient: 0. # claforte: would require normals, which is costly in VRAM and needs more changes in code/yaml
    lambda_sparsity: 10. # 2.0 was 10.
    lambda_opaque: [10000, 0.0, 1000.0, 10001] # [0, 1., 20., 5000] # was [10000, 0.0, 1000.0, 10001]
    lambda_z_variance: 0.
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-8
    # name: Adan
    # args:
    #   lr: 0.01
    #   max_grad_norm: 5.0
    #   eps: 1.e-8
    #   weight_decay: 1e-5
    params:
      geometry.encoding:
        lr: 0.01
      geometry.density_network:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001
      guidance:
        lr: 0.0001

trainer:
  max_steps: 25000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
