name: "zero123"
tag: "${data.random_camera.height}_${rmspace:${basename:${data.image_path}},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "single-image-datamodule"
data: # threestudio/data/image.py -> SingleImageDataModuleConfig
  image_path: ./load/images/hamburger_rgba.png
  height: 192
  width: 192
  default_elevation_deg: 0.0
  default_azimuth_deg: 0.0
  default_camera_distance: 3.2
  default_fovy_deg: 20.0
  random_camera: # threestudio/data/uncond.py -> RandomCameraDataModuleConfig
    height: 128
    width: 128
    eval_height: 256
    eval_width: 256
    batch_size: 2
    eval_batch_size: 1
    elevation_range: [-10, 60]
    azimuth_range: [-180, 180]
    camera_distance_range: [3.2, 3.3]
    fovy_range: [20.0, 20.0] # Zero123 has fixed fovy
    camera_perturb: 0.0
    center_perturb: 0.0
    up_perturb: 0.0
    light_position_perturb: 1.0
    light_distance_range: [7.5, 10.0]
    eval_elevation_deg: ${data.default_elevation_deg}
    eval_camera_distance: ${data.default_camera_distance}
    eval_fovy_deg: ${data.default_fovy_deg}
    light_sample_strategy: "dreamfusion"
    batch_uniform_azimuth: False
    n_val_views: 30
    n_test_views: 120

system_type: "zero123-system"
system:
  geometry_type: "implicit-volume"
  geometry:
    radius: 2.0
    normal_type: "analytic"

    # the density initialization proposed in the DreamFusion paper
    # does not work very well
    # density_bias: "blob_dreamfusion"
    # density_activation: exp
    # density_blob_scale: 5.
    # density_blob_std: 0.2

    # use Magic3D density initialization instead
    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    # coarse to fine hash grid encoding
    # to ensure smooth analytic normals
    pos_encoding_config:
      otype: ProgressiveBandHashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096
      start_level: 8 # resolution ~200
      start_step: 2000
      update_steps: 500

  material_type: "diffuse-with-point-light-material"
  material:
    ambient_only_steps: 100000
    textureless_prob: 0.05
    albedo_activation: sigmoid

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    return_comp_normal: ${gt0:${system.loss.lambda_normal_smooth}}
    return_normal_perturb: ${gt0:${system.loss.lambda_3d_normal_smooth}}

  prompt_processor_type: "zero123-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: ""
    prompt: ""

  guidance_type: "zero123-guidance"
  guidance:
    pretrained_model_name_or_path: "./load/zero123/105000.ckpt"
    pretrained_config: "./load/zero123/sd-objaverse-finetune-c_concat-256.yaml"
    vram_O: ${not:${gt0:${system.freq.guidance_eval}}}
    cond_image_path: ${data.image_path}
    cond_elevation_deg: ${data.default_elevation_deg}
    cond_azimuth_deg: ${data.default_azimuth_deg}
    cond_camera_distance: ${data.default_camera_distance}
    guidance_scale: 3.0
    min_step_percent: 0.02
    # min_step_percent: [0, 0.66, 0.33, 2000]  # (start_iter, start_val, end_val, end_iter)
    max_step_percent: 0.98
    # max_step_percent: [0, 0.98, 0.66, 2000]

  freq:
    n_ref: 2
    ref_only_steps: 0
    guidance_eval: 0  # must not be a multiple of system.freq.n_ref
    ref_or_zero123: "alternate" # can be "accumulate" or "alternate"

  loggers:
    wandb:
      enable: false
      project: "threestudio"

  loss:
    lambda_sds: 0.003
    lambda_rgb: 200.
    lambda_mask: 50.
    lambda_depth: 1.
    lambda_normal_smooth: 0.0
    lambda_3d_normal_smooth: 0.5
    lambda_orient: [0, 1., 20., 5000]
    lambda_sparsity: 2.0 # should be tweaked for every model
    lambda_opaque: 0.5

  optimizer:
    name: Adan
    args:
      lr: 0.01
      max_grad_norm: 5.0
      eps: 1.e-8
      weight_decay: 1e-5
    params:
      geometry:
        lr: ${system.optimizer.args.lr}
      background:
        lr: ${system.optimizer.args.lr}

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
